parameters:
    teckhouse_mdetect.wrapper_class: TeckHouse\MDetectBundle\MDetect\MDetect

services:
    teckhouse_mdetect.wrapper:
        class: %teckhouse_mdetect.wrapper_class%
                
    teckhouse_mdetect.twig.device_detect_extension:
        class: TeckHouse\MDetectBundle\Twig\DeviceDetectExtension
        arguments: ["@teckhouse_mdetect.wrapper"]
        tags:
            - { name: twig.extension }